### ISSUE TITLE
bug: 'Rich Editor' fields 

### ISSUE THREAD

**Issue by ryanrussell** [patmood/pocketbase-typegen#63]
Hey,

Hello,

I may have stumbled on an edge case that's not handled around the "Rich Editor" fields.

```bash
npx pocketbase-typegen --db /path/to/data.db --out /path/to/generated-types.ts
file:///tmp/project-path/node_modules/.pnpm/pocketbase-typegen@1.1.2/node_modules/pocketbase-typegen/dist/index.js:202
    throw new Error(`unknown type ${fieldSchema.type} found in schema`);
          ^

Error: unknown type editor found in schema
    at createTypeField (file:///tmp/project-path/node_modules/.pnpm/pocketbase-typegen@1.1.2/node_modules/pocketbase-typegen/dist/index.js:202:11)
    at file:///tmp/project-path/node_modules/.pnpm/pocketbase-typegen@1.1.2/node_modules/pocketbase-typegen/dist/index.js:187:46
    at Array.map (<anonymous>)
    at createRecordType (file:///tmp/project-path/node_modules/.pnpm/pocketbase-typegen@1.1.2/node_modules/pocketbase-typegen/dist/index.js:187:25)
    at file:///tmp/project-path/node_modules/.pnpm/pocketbase-typegen@1.1.2/node_modules/pocketbase-typegen/dist/index.js:152:24
    at Array.forEach (<anonymous>)
    at generate (file:///tmp/project-path/node_modules/.pnpm/pocketbase-typegen@1.1.2/node_modules/pocketbase-typegen/dist/index.js:148:6)
    at main (file:///tmp/project-path/node_modules/.pnpm/pocketbase-typegen@1.1.2/node_modules/pocketbase-typegen/dist/index.js:235:22)
```

```bash
npx pocketbase-typegen --version
1.1.2
node --version
v18.16.0
```

This happens when you add a "RIch editor" field in pb like:
![image](https://user-images.githubusercontent.com/523300/237049709-68b4748e-b188-4031-b947-c68896974ddc.png)

To recreate:
```sql
-- users table because I have a fk in organizations
CREATE TABLE users (
    avatar                 TEXT    DEFAULT '',
    created                TEXT    DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ') ) 
                                   NOT NULL,
    email                  TEXT    DEFAULT ''
                                   NOT NULL,
    emailVisibility        BOOLEAN DEFAULT FALSE
                                   NOT NULL,
    id                     TEXT    PRIMARY KEY
                                   DEFAULT ('r' || lower(hex(randomblob(7) ) ) ) 
                                   NOT NULL,
    lastResetSentAt        TEXT    DEFAULT ''
                                   NOT NULL,
    lastVerificationSentAt TEXT    DEFAULT ''
                                   NOT NULL,
    name                   TEXT    DEFAULT '',
    passwordHash           TEXT    NOT NULL,
    tokenKey               TEXT    NOT NULL,
    updated                TEXT    DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ') ) 
                                   NOT NULL,
    username               TEXT    NOT NULL,
    verified               BOOLEAN DEFAULT FALSE
                                   NOT NULL
);

-- This works without the notes field; but not with
CREATE TABLE organizations (
    created  TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ') ) 
                  NOT NULL,
    user_id  TEXT DEFAULT '',
    id       TEXT PRIMARY KEY
                  DEFAULT ('r' || lower(hex(randomblob(7) ) ) ) 
                  NOT NULL,
    org_name TEXT DEFAULT '',
    updated  TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ') ) 
                  NOT NULL,
    notes    TEXT DEFAULT ''
);


```

Here's the schema for `organizations` from `_collections`
```json
[{"system":false,"id":"ljotmdnm","name":"org_name","type":"text","required":false,"unique":false,"options":{"min":null,"max":null,"pattern":""}},{"system":false,"id":"wihxxtjx","name":"user_id","type":"relation","required":false,"unique":false,"options":{"collectionId":"_pb_users_auth_","cascadeDelete":false,"minSelect":null,"maxSelect":1,"displayFields":[]}},{"system":false,"id":"agpbrqrf","name":"notes","type":"editor","required":true,"unique":false,"options":{}}]
```

Tried allowing and not allowing nulls in the "Rich editor" field, did not seem to matter either way:
![image](https://user-images.githubusercontent.com/523300/237053108-a37b70aa-b0f2-43a1-85d3-e8f4b16c54d9.png)

I'm not deeply familiar with pocketbase, it's very possible I'm doing something silly... but I don't see much different in the raw schema between these "Rich notes" fields and a normal text field.

I can confirm if I delete the "notes" field, `pocketbase-typegen` works again.

Any suggestions on how to get this working would be greatly appreciated.

**Comment by ryanrussell** [comment]
I was using an old version `1.1.2` instead of `1.1.9`, where this is already fixed like

```
editor: HTML_STRING_NAME,
```

Great work; only issue here is I had an old version pinned.

**Comment by patmood** [comment]
Thanks for the very detailed bug report! I've been careful to keep all the updates backwards compatible and the new version will capture many more fixes. Enjoy!
